# use run or skip
unit_tests: skip
channel_sources:
  - deepmodeling/label/dev,deepmodeling,https://conda.deepmodeling.org/,defaults
channel_targets:
  - ambertoolsml main
libnetcdf:
- 4.6.1
dp_version:
- 2.0.0.b4
boost_cpp:
- 1.73.0
